FROM node:22-bookworm-slim

WORKDIR /app

# Install required tools
RUN apt update && apt install -y openssl libssl-dev

COPY package*.json ./
RUN npm install
RUN npm install -g serve

COPY . .

RUN npm run build

EXPOSE 5173

CMD [ "serve", "-s", "dist", "-l", "5173" ]
