# ========= Builder
FROM node:22-bookworm-slim AS builder

WORKDIR /app

RUN apt update && \
    apt install -y libssl-dev openssl sqlite3 && \
    rm -rf /var/lib/apt/lists/*

COPY *.json prisma ./

RUN npm install

COPY . .

RUN npm run build

# ========== Production
FROM node:22-bookworm-slim

WORKDIR /app

RUN apt update && \ 
    apt install -y libssl-dev openssl sqlite3 && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
RUN npx prisma generate

EXPOSE 3000

CMD [ "node", "dist/server.js" ]
